parameters:
    app.types:
        App:
            Person:
                Diet:
                    VEGAN:
                        label: "Vegan"
                        chooseable: true
                    VEGETARIAN:
                        label: "Vegetarian"
                        chooseable: true
                    NO-PORK:
                        label: "No pork"
                        chooseable: true
                    LACTOSE:
                        label: "Lactose intolerant"
                        chooseable: true
                    GLUTEN:
                        label: "Gluten intolerant"
                        chooseable: true
